<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.group2.fse</groupId>
    <artifactId>coobs-backend-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>CooBS Core Banking Backend Aggregator</name>
    <description>Root Maven aggregator for CooBS microservices</description>

    <modules>
        <module>api-gateway</module>
        <module>auth-service</module>
        <module>account-service</module>
        <module>ledger-service</module>
        <module>notification-service</module>
        <module>audit-service</module>
    </modules>
</project>
