spring.application.name=ledger-service

spring.datasource.url=jdbc:oracle:thin:@localhost:${ORACLE_PORT}/${ORACLE_DATABASE}
spring.datasource.username=${APP_USER}
spring.datasource.password=${APP_USER_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=5

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true