spring.application.name=ledger-service

# ==============================================================================
# Primary Datasource: Oracle (Master System of Record & Row Locks -> JPA)
# ==============================================================================
spring.datasource.url=jdbc:oracle:thin:@localhost:${ORACLE_PORT:1521}/${ORACLE_DATABASE:XEPDB1}
spring.datasource.username=${APP_USER:core_user}
spring.datasource.password=${APP_USER_PASSWORD:CorePassword123!}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=5

# ==============================================================================
# Secondary Datasource: PostgreSQL (Immutable Forensic Audit Store -> JdbcTemplate)
# ==============================================================================
postgres.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT:5434}/${POSTGRES_DB:audit_store}
postgres.datasource.username=${POSTGRES_USER:postgres}
postgres.datasource.password=${POSTGRES_PASSWORD:AuditPassword123!}
postgres.datasource.driver-class-name=org.postgresql.Driver

# ==============================================================================
# JPA / Hibernate Configurations
# ==============================================================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# ==============================================================================
# Redis Configuration (Distributed Idempotency Mutex & Balance Cache)
# ==============================================================================
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.timeout=2000ms